### PR TITLE
Refactor muti-file support

### PR DESCRIPTION
**Pull request by ppaul12**
A brief summary
- Added:
    - configer: yaml file reader, only stores the options, dataframe excluded
    - packer: results and reference data packer, finishes all adjustment and pre-calculation
    - plotter: graph plotter, plots necessary graphs one by one
- Ignored: plot of progress info, due to the uncertain column "bottom" https://github.com/MapIV/localization_evaluation_toolkit/blob/697bdd50f10fb1b1dd0d5ebe1787b4456ea9b38b/scripts/util/plot.py#L76
- Pending: rosbag part, extensible configer might be useful

Thanks a lot!

### CODE REVIEW

**Comment by KOKIAOKI** [comment]
Thank you for your PR.
Could you test the following three files?

- Reference
~/localization_evaluation_toolkit/sample_data/reference.csv
- Result1
~/localization_evaluation_toolkit/sample_data/result_trj_ndt.csv
- Result2
~/localization_evaluation_toolkit/sample_data/result_trj_ekf.csv

When I test main.py with these files and attached yaml file, error occured.
[sasashima_evaluation.zip](https://github.com/MapIV/localization_evaluation_toolkit/files/10291315/sasashima_evaluation.zip)
```
$ python3 main.py '/home/koki/test2/localization_evaluation_toolkit/sample_data/config/sasashima_evaluation.yaml' 
Loading yaml file ...Completed!!
Loading csv files ...Traceback (most recent call [last):]([url](url))
  File "main.py", line 16, in <module>
    ref_pack, res_packs = packer.param2pack(ref_param, res_params, opt_param)
  File "/home/koki/test2/localization_evaluation_toolkit/scripts/util/packer.py", line 313, in param2pack
    ref_pack = RefDataPack.build_from_res(ref_parm, opt_param, res_packs)
  File "/home/koki/test2/localization_evaluation_toolkit/scripts/util/packer.py", line 303, in build_from_res
    ref_df = cls.accumulate_df([res_pack.data_ref for res_pack in res_packs])
  File "/home/koki/test2/localization_evaluation_toolkit/scripts/util/packer.py", line 309, in accumulate_df
    return pd.concat(dfs, ignore_index=True).drop_duplicates().sort_values(by=sort_by, ignore_index=True)
TypeError: sort_values() got an unexpected keyword argument 'ignore_index'

```

**Comment by KOKIAOKI** [comment]
In addition, after you test three csv files, could you update the chapter "What graphs are output?" in README? Command and outputed figures should be updated.
Update  sample_data/config/sasashima_evaluation.yaml also. When you update this yaml file, you can rename as you like.

**Comment by ppaul12** [comment]
Thanks for your review. README file was updated.
I have tested the given data files on both Mac OS and Ubuntu 22.04 with

|| Mac OS | Ubuntu 20.04 |
|-|-|-|
| python3 | 3.10.6 | 3.8.10 |
| numpy | 1.23.1 | 1.23.5 |
| pandas | 1.5.1 | 1.5.2 |
| matplotlib | 3.6.2 | 3.6.2 |

but I failed to reproduce the [aforementioned error](https://github.com/MapIV/localization_evaluation_toolkit/pull/3#issuecomment-1363493174). After checking the document of pandas, it seems that the parameter `ignore_index` of function `sort_values` was introduced since the first stable release, and I am a little bit confused as well.

**Comment by KOKIAOKI** [comment]
Thank you for providing additional information. I could test "main.py" with anaconda (about python 3.9).
I comfirmed that graphs were outputed correctly.
Could you write the minimum python version in README?　(maybe python 3.8.10)
After you fix it, I will merge your PR.

**Comment by ppaul12** [comment]
Sorry for delaying. The last commit might work fine under Python3 (python3.9 dependent line revised) after checking the syntax again.

> from: https://github.com/PENG-AO/localization_evaluation_toolkit/blob/d70694ab79bb4a907770e83c43dd8b03be6fd321/scripts/util/plotter.py#L273
> to: https://github.com/PENG-AO/localization_evaluation_toolkit/blob/b3af72cb2911d6ed6905a5eaadf8d4c4b614c36c/scripts/util/plotter.py#L273

**Pull request merged**
